// @ts-nocheck
/* eslint-disable */
/* tslint:disable */
/* prettier-ignore-start */
/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */
// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: nFjNKQj52vQ71pvQo3gqEb
// Component: Y89cMq9IGP
import * as React from "react";
import * as p from "@plasmicapp/react-web";
import * as ph from "@plasmicapp/react-web/lib/host";
import {
  hasVariant,
  classNames,
  createPlasmicElementProxy,
  deriveRenderOpts,
  ensureGlobalVariants
} from "@plasmicapp/react-web";
import Button2 from "../../Button2"; // plasmic-import: Zkw7kzOJlBe/component
import { useScreenVariants as useScreenVariants_6HrcQsCevL9L7 } from "./PlasmicGlobalVariant__Screen"; // plasmic-import: 6HrcQSCevL9L7/globalVariant
import "@plasmicapp/react-web/lib/plasmic.css";
import projectcss from "./plasmic_minimalist_about_me_page.module.css"; // plasmic-import: nFjNKQj52vQ71pvQo3gqEb/projectcss
import sty from "./PlasmicFeaturesPage.module.css"; // plasmic-import: Y89cMq9IGP/css
import Icon4Icon from "./icons/PlasmicIcon__Icon4"; // plasmic-import: AWJIE_47fRh/icon
import Icon5Icon from "./icons/PlasmicIcon__Icon5"; // plasmic-import: xsjOeRsaZYU/icon
import ChecksvgIcon from "./icons/PlasmicIcon__Checksvg"; // plasmic-import: 6_5mJVAw_mw/icon
import Icon16Icon from "./icons/PlasmicIcon__Icon16"; // plasmic-import: HkdywyjX_0b/icon
import ArrowRightsvgIcon from "./icons/PlasmicIcon__ArrowRightsvg"; // plasmic-import: wtE3ARFhA0u/icon
import image388TA5T29I3M from "./images/image38.jpeg"; // plasmic-import: 8t_A5t29I3M/picture
import image39W9ZP9DUaIuT from "./images/image39.jpeg"; // plasmic-import: W9zP9dUaIuT/picture
import image41V5ADj4V6Z9I from "./images/image41.jpeg"; // plasmic-import: V5ADj4V6z9i/picture
import image42CDeLRjSyJqx from "./images/image42.jpeg"; // plasmic-import: CDeLRjSyJqx/picture
import image431JzadiWRtpu from "./images/image43.jpeg"; // plasmic-import: 1jzadiWRtpu/picture

export const PlasmicFeaturesPage__VariantProps = new Array();

export const PlasmicFeaturesPage__ArgProps = new Array();

const __wrapUserFunction =
  globalThis.__PlasmicWrapUserFunction ?? ((loc, fn) => fn());

const __wrapUserPromise =
  globalThis.__PlasmicWrapUserPromise ??
  (async (loc, promise) => {
    return await promise;
  });

function PlasmicFeaturesPage__RenderFunc(props) {
  const { variants, overrides, forNode } = props;
  const $ctx = ph.useDataEnv?.() || {};
  const args = React.useMemo(() => Object.assign({}, props.args), [props.args]);
  const $props = {
    ...args,
    ...variants
  };
  const refsRef = React.useRef({});
  const $refs = refsRef.current;
  const currentUser = p.useCurrentUser?.() || {};
  const [$queries, setDollarQueries] = React.useState({});
  const globalVariants = ensureGlobalVariants({
    screen: useScreenVariants_6HrcQsCevL9L7()
  });
  return (
    <React.Fragment>
      <div className={projectcss.plasmic_page_wrapper}>
        <p.Stack
          as={"div"}
          data-plasmic-name={"root"}
          data-plasmic-override={overrides.root}
          data-plasmic-root={true}
          data-plasmic-for-node={forNode}
          hasGap={true}
          className={classNames(
            projectcss.all,
            projectcss.root_reset,
            projectcss.plasmic_default_styles,
            projectcss.plasmic_mixins,
            projectcss.plasmic_tokens,
            sty.root
          )}
        >
          <div className={classNames(projectcss.all, sty.freeBox__qmuI4)}>
            <div className={classNames(projectcss.all, sty.freeBox__l7PS)}>
              <p.Stack
                as={"div"}
                hasGap={true}
                className={classNames(projectcss.all, sty.freeBox___6E8Os)}
              >
                <p.Stack
                  as={"div"}
                  hasGap={true}
                  className={classNames(projectcss.all, sty.freeBox__f1EU4)}
                >
                  {true ? (
                    <a
                      className={classNames(
                        projectcss.all,
                        projectcss.a,
                        sty.link__tiaZx
                      )}
                    >
                      <Icon4Icon
                        className={classNames(projectcss.all, sty.svg__ja1H)}
                        role={"img"}
                      />
                    </a>
                  ) : null}

                  <p.Stack
                    as={"div"}
                    hasGap={true}
                    className={classNames(projectcss.all, sty.freeBox__apzLq)}
                  >
                    <p.Stack
                      as={"a"}
                      hasGap={true}
                      className={classNames(
                        projectcss.all,
                        projectcss.a,
                        sty.link__vdJWn
                      )}
                    >
                      {false ? (
                        <Icon5Icon
                          className={classNames(projectcss.all, sty.svg__qBw2)}
                          role={"img"}
                        />
                      ) : null}

                      <div
                        className={classNames(
                          projectcss.all,
                          projectcss.__wab_text,
                          sty.text__vlSn
                        )}
                      >
                        {"About Us"}
                      </div>

                      {false ? (
                        <Icon5Icon
                          className={classNames(projectcss.all, sty.svg__bnO1G)}
                          role={"img"}
                        />
                      ) : null}
                    </p.Stack>

                    <p.Stack
                      as={"a"}
                      hasGap={true}
                      className={classNames(
                        projectcss.all,
                        projectcss.a,
                        sty.link__f4Yqk
                      )}
                    >
                      {false ? (
                        <Icon5Icon
                          className={classNames(projectcss.all, sty.svg__o0Oj0)}
                          role={"img"}
                        />
                      ) : null}

                      <div
                        className={classNames(
                          projectcss.all,
                          projectcss.__wab_text,
                          sty.text__gmbPi
                        )}
                      >
                        {"Features"}
                      </div>

                      {false ? (
                        <Icon5Icon
                          className={classNames(
                            projectcss.all,
                            sty.svg___1Arxi
                          )}
                          role={"img"}
                        />
                      ) : null}
                    </p.Stack>

                    <p.Stack
                      as={"a"}
                      hasGap={true}
                      className={classNames(
                        projectcss.all,
                        projectcss.a,
                        sty.link__fnw8V
                      )}
                    >
                      {false ? (
                        <Icon5Icon
                          className={classNames(
                            projectcss.all,
                            sty.svg___4Mf1X
                          )}
                          role={"img"}
                        />
                      ) : null}

                      <div
                        className={classNames(
                          projectcss.all,
                          projectcss.__wab_text,
                          sty.text___3MGjH
                        )}
                      >
                        {"Pricing "}
                      </div>

                      {false ? (
                        <Icon5Icon
                          className={classNames(projectcss.all, sty.svg__hyy9L)}
                          role={"img"}
                        />
                      ) : null}
                    </p.Stack>

                    <p.Stack
                      as={"a"}
                      hasGap={true}
                      className={classNames(
                        projectcss.all,
                        projectcss.a,
                        sty.link__nz8Jm
                      )}
                    >
                      {false ? (
                        <Icon5Icon
                          className={classNames(
                            projectcss.all,
                            sty.svg___1SzZz
                          )}
                          role={"img"}
                        />
                      ) : null}

                      <div
                        className={classNames(
                          projectcss.all,
                          projectcss.__wab_text,
                          sty.text__joOy
                        )}
                      >
                        {"Contact"}
                      </div>

                      {false ? (
                        <Icon5Icon
                          className={classNames(projectcss.all, sty.svg__lquRh)}
                          role={"img"}
                        />
                      ) : null}
                    </p.Stack>

                    <p.Stack
                      as={"a"}
                      hasGap={true}
                      className={classNames(
                        projectcss.all,
                        projectcss.a,
                        sty.link__aw80N
                      )}
                    >
                      {false ? (
                        <Icon5Icon
                          className={classNames(projectcss.all, sty.svg__x8A4I)}
                          role={"img"}
                        />
                      ) : null}

                      <div
                        className={classNames(
                          projectcss.all,
                          projectcss.__wab_text,
                          sty.text__eF2Rr
                        )}
                      >
                        {"Blog"}
                      </div>

                      {false ? (
                        <Icon5Icon
                          className={classNames(projectcss.all, sty.svg__t58Hc)}
                          role={"img"}
                        />
                      ) : null}
                    </p.Stack>

                    <Button2
                      className={classNames(
                        "__wab_instance",
                        sty.button2__lHMly
                      )}
                      endIcon={
                        <ChecksvgIcon
                          className={classNames(projectcss.all, sty.svg__k6ZIz)}
                          role={"img"}
                        />
                      }
                      shape={"rounded"}
                      startIcon={
                        <ChecksvgIcon
                          className={classNames(projectcss.all, sty.svg__kMsAa)}
                          role={"img"}
                        />
                      }
                    >
                      <div
                        className={classNames(
                          projectcss.all,
                          projectcss.__wab_text,
                          sty.text___4TL3E
                        )}
                      >
                        {"Get started"}
                      </div>
                    </Button2>
                  </p.Stack>
                </p.Stack>
              </p.Stack>
            </div>
          </div>

          <div
            data-plasmic-name={"pageBanner"}
            data-plasmic-override={overrides.pageBanner}
            className={classNames(projectcss.all, sty.pageBanner)}
          >
            <div className={classNames(projectcss.all, sty.freeBox__jNBly)}>
              <p.Stack
                as={"div"}
                hasGap={true}
                className={classNames(projectcss.all, sty.columns___0Tl91)}
              >
                <div className={classNames(projectcss.all, sty.column__pcfls)}>
                  <p.Stack
                    as={"div"}
                    hasGap={true}
                    className={classNames(projectcss.all, sty.freeBox__lefli)}
                  >
                    <h1
                      data-plasmic-name={"h1"}
                      data-plasmic-override={overrides.h1}
                      className={classNames(
                        projectcss.all,
                        projectcss.h1,
                        projectcss.__wab_text,
                        sty.h1
                      )}
                    >
                      {"Our Features "}
                    </h1>

                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text__aWlh3
                      )}
                    >
                      {
                        "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam,"
                      }
                    </div>
                  </p.Stack>
                </div>

                <div className={classNames(projectcss.all, sty.column__sy7Nr)}>
                  <p.PlasmicImg
                    alt={""}
                    className={classNames(sty.img__bWvyY)}
                    displayHeight={"auto"}
                    displayMaxHeight={"none"}
                    displayMaxWidth={
                      hasVariant(globalVariants, "screen", "mobileOnly")
                        ? "100%"
                        : "100%"
                    }
                    displayMinHeight={"0"}
                    displayMinWidth={"0"}
                    displayWidth={"auto"}
                    loading={
                      hasVariant(globalVariants, "screen", "mobileOnly")
                        ? "lazy"
                        : "lazy"
                    }
                    src={
                      hasVariant(globalVariants, "screen", "mobileOnly")
                        ? {
                            src: image39W9ZP9DUaIuT,
                            fullWidth: 700,
                            fullHeight: 466,
                            aspectRatio: undefined
                          }
                        : {
                            src: image388TA5T29I3M,
                            fullWidth: 1920,
                            fullHeight: 1280,
                            aspectRatio: undefined
                          }
                    }
                  />
                </div>
              </p.Stack>
            </div>
          </div>

          <div className={classNames(projectcss.all, sty.freeBox___8Lr9Y)}>
            <p.Stack
              as={"section"}
              data-plasmic-name={"section"}
              data-plasmic-override={overrides.section}
              hasGap={true}
              className={classNames(projectcss.all, sty.section)}
            >
              <p.Stack
                as={"div"}
                data-plasmic-name={"foreground"}
                data-plasmic-override={overrides.foreground}
                hasGap={true}
                className={classNames(projectcss.all, sty.foreground)}
              >
                <p.Stack
                  as={"div"}
                  hasGap={true}
                  className={classNames(projectcss.all, sty.freeBox__l2Zv5)}
                >
                  <h3
                    className={classNames(
                      projectcss.all,
                      projectcss.h3,
                      projectcss.__wab_text,
                      sty.h3__jdarL
                    )}
                  >
                    {"The standard Lorem Ipsum passage"}
                  </h3>

                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__zjhvr
                    )}
                  >
                    {
                      "Vitae sed sem a justo mauris potenti a primis vivamus justo tempor viverra adipiscing convallis fusce odio condimentum mi parturient ultricies."
                    }
                  </div>

                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__eB0Ks
                    )}
                  >
                    {
                      "Vitae sed sem a justo mauris potenti a primis vivamus justo tempor viverra adipiscing convallis fusce odio condimentum mi parturient ultricies."
                    }
                  </div>
                </p.Stack>

                <div
                  className={classNames(projectcss.all, sty.freeBox___596Ne)}
                >
                  <div
                    className={classNames(projectcss.all, sty.freeBox__gpuQg)}
                  >
                    <h5
                      className={classNames(
                        projectcss.all,
                        projectcss.h5,
                        projectcss.__wab_text,
                        sty.h5__mzwsn
                      )}
                    >
                      {"Built on capability"}
                    </h5>

                    <Icon16Icon
                      className={classNames(projectcss.all, sty.svg___2Xuvw)}
                      role={"img"}
                    />
                  </div>

                  <div
                    className={classNames(projectcss.all, sty.freeBox___3IWf)}
                  >
                    <h5
                      className={classNames(
                        projectcss.all,
                        projectcss.h5,
                        projectcss.__wab_text,
                        sty.h5__iXx6V
                      )}
                    >
                      {"Highly energetic"}
                    </h5>

                    <Icon16Icon
                      className={classNames(projectcss.all, sty.svg__so8Cr)}
                      role={"img"}
                    />
                  </div>

                  <div
                    className={classNames(projectcss.all, sty.freeBox__raAqW)}
                  >
                    <h5
                      className={classNames(
                        projectcss.all,
                        projectcss.h5,
                        projectcss.__wab_text,
                        sty.h5__i0XfV
                      )}
                    >
                      {"100% transparency and accountability"}
                    </h5>

                    <Icon16Icon
                      className={classNames(projectcss.all, sty.svg__hnM6Z)}
                      role={"img"}
                    />
                  </div>

                  <div
                    className={classNames(projectcss.all, sty.freeBox__kcdGf)}
                  >
                    <h5
                      className={classNames(
                        projectcss.all,
                        projectcss.h5,
                        projectcss.__wab_text,
                        sty.h5__fEao3
                      )}
                    >
                      {"Refreshing clarity"}
                    </h5>

                    <Icon16Icon
                      className={classNames(projectcss.all, sty.svg__jtUsJ)}
                      role={"img"}
                    />
                  </div>

                  <div
                    className={classNames(projectcss.all, sty.freeBox__pqnZr)}
                  >
                    <h5
                      className={classNames(
                        projectcss.all,
                        projectcss.h5,
                        projectcss.__wab_text,
                        sty.h5__pKr9P
                      )}
                    >
                      {"Modern results"}
                    </h5>

                    <Icon16Icon
                      className={classNames(projectcss.all, sty.svg__qxrLz)}
                      role={"img"}
                    />
                  </div>
                </div>
              </p.Stack>
            </p.Stack>

            <div className={classNames(projectcss.all, sty.freeBox__l8UhO)}>
              <p.Stack
                as={"div"}
                hasGap={true}
                className={classNames(projectcss.all, sty.freeBox__v41Jz)}
              >
                <div className={classNames(projectcss.all, sty.freeBox__opz0N)}>
                  <div
                    className={classNames(projectcss.all, sty.freeBox__rvMsT)}
                  >
                    <p.Stack
                      as={"div"}
                      hasGap={true}
                      className={classNames(projectcss.all, sty.freeBox__aje8S)}
                    >
                      <p.Stack
                        as={"div"}
                        data-plasmic-name={"copy"}
                        data-plasmic-override={overrides.copy}
                        hasGap={true}
                        className={classNames(projectcss.all, sty.copy)}
                      >
                        <p.Stack
                          as={"div"}
                          hasGap={true}
                          className={classNames(
                            projectcss.all,
                            sty.freeBox__unot4
                          )}
                        >
                          <div
                            className={classNames(
                              projectcss.all,
                              projectcss.__wab_text,
                              sty.text__qsBip
                            )}
                          >
                            {"Welcome"}
                          </div>

                          <h3
                            className={classNames(
                              projectcss.all,
                              projectcss.h3,
                              projectcss.__wab_text,
                              sty.h3__pcDr
                            )}
                          >
                            {"The standard Lorem "}
                          </h3>

                          <div
                            className={classNames(
                              projectcss.all,
                              projectcss.__wab_text,
                              sty.text__mbGpu
                            )}
                          >
                            {
                              "Vitae sed sem a justo mauris potenti a primis vivamus justo tempor viverra adipiscing convallis fusce odio condimentum mi parturient ultricies."
                            }
                          </div>
                        </p.Stack>

                        <p.Stack
                          as={"div"}
                          hasGap={true}
                          className={classNames(
                            projectcss.all,
                            sty.freeBox__hfl7G
                          )}
                        >
                          <Button2
                            className={classNames(
                              "__wab_instance",
                              sty.button2__azPQx
                            )}
                            color={"blue"}
                            endIcon={
                              <ArrowRightsvgIcon
                                className={classNames(
                                  projectcss.all,
                                  sty.svg__hmdmb
                                )}
                                role={"img"}
                              />
                            }
                            shape={"rounded"}
                            showEndIcon={true}
                            startIcon={
                              <ChecksvgIcon
                                className={classNames(
                                  projectcss.all,
                                  sty.svg__yA1Zk
                                )}
                                role={"img"}
                              />
                            }
                          >
                            <div
                              className={classNames(
                                projectcss.all,
                                projectcss.__wab_text,
                                sty.text__xjNpn
                              )}
                            >
                              {"Start Now"}
                            </div>
                          </Button2>
                        </p.Stack>
                      </p.Stack>
                    </p.Stack>
                  </div>

                  <div
                    data-plasmic-name={"art"}
                    data-plasmic-override={overrides.art}
                    className={classNames(projectcss.all, sty.art)}
                  >
                    <p.PlasmicImg
                      alt={""}
                      className={classNames(sty.img__gdMLr)}
                      displayHeight={"100%"}
                      displayMaxHeight={"none"}
                      displayMaxWidth={"none"}
                      displayMinHeight={"0"}
                      displayMinWidth={"0"}
                      displayWidth={"100%"}
                      src={
                        "https://images.unsplash.com/photo-1520333789090-1afc82db536a?ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&ixlib=rb-1.2.1&auto=format&fit=crop&w=2851&q=80"
                      }
                    />

                    <div
                      className={classNames(projectcss.all, sty.freeBox__coI6G)}
                    />
                  </div>
                </div>
              </p.Stack>
            </div>
          </div>

          <div className={classNames(projectcss.all, sty.freeBox___6SNh2)}>
            <div className={classNames(projectcss.all, sty.columns___3V4Ng)}>
              <div className={classNames(projectcss.all, sty.column__m6KZ9)}>
                <h2
                  data-plasmic-name={"h2"}
                  data-plasmic-override={overrides.h2}
                  className={classNames(
                    projectcss.all,
                    projectcss.h2,
                    projectcss.__wab_text,
                    sty.h2
                  )}
                >
                  {"Make your call to action here."}
                </h2>

                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text___5Huqg
                  )}
                >
                  {"Lorem ipsum dolor sit amet, consectetur adipiscing elit."}
                </div>

                <Button2
                  className={classNames("__wab_instance", sty.button2__a6S)}
                  color={"blue"}
                  endIcon={
                    <ArrowRightsvgIcon
                      className={classNames(projectcss.all, sty.svg__fqaEf)}
                      role={"img"}
                    />
                  }
                  shape={"rounded"}
                  showEndIcon={true}
                  startIcon={
                    <ChecksvgIcon
                      className={classNames(projectcss.all, sty.svg__yEq2)}
                      role={"img"}
                    />
                  }
                >
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text___7XzM7
                    )}
                  >
                    {"Start Now"}
                  </div>
                </Button2>
              </div>
            </div>
          </div>

          <div className={classNames(projectcss.all, sty.freeBox__o1W5U)}>
            <div
              data-plasmic-name={"footerTop"}
              data-plasmic-override={overrides.footerTop}
              className={classNames(projectcss.all, sty.footerTop)}
            >
              <div
                data-plasmic-name={"container"}
                data-plasmic-override={overrides.container}
                className={classNames(projectcss.all, sty.container)}
              >
                <div className={classNames(projectcss.all, sty.columns__nYaN)}>
                  <p.Stack
                    as={"div"}
                    hasGap={true}
                    className={classNames(projectcss.all, sty.column__pqiB)}
                  >
                    <Icon4Icon
                      className={classNames(projectcss.all, sty.svg__tzAsL)}
                      role={"img"}
                    />

                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text__w3AU
                      )}
                    >
                      {
                        "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s"
                      }
                    </div>
                  </p.Stack>

                  <div className={classNames(projectcss.all, sty.column__xwum)}>
                    <h5
                      className={classNames(
                        projectcss.all,
                        projectcss.h5,
                        projectcss.__wab_text,
                        sty.h5___2PDtb
                      )}
                    >
                      {"Menu"}
                    </h5>

                    <a
                      className={classNames(
                        projectcss.all,
                        projectcss.a,
                        projectcss.__wab_text,
                        sty.link___4Zgtd
                      )}
                    >
                      {"Privacy Policy"}
                    </a>

                    <a
                      className={classNames(
                        projectcss.all,
                        projectcss.a,
                        projectcss.__wab_text,
                        sty.link___3Pn
                      )}
                    >
                      {"Terms of Service"}
                    </a>

                    <a
                      className={classNames(
                        projectcss.all,
                        projectcss.a,
                        projectcss.__wab_text,
                        sty.link__xXDtS
                      )}
                    >
                      {"Pricing "}
                    </a>

                    <a
                      className={classNames(
                        projectcss.all,
                        projectcss.a,
                        projectcss.__wab_text,
                        sty.link__v8T9P
                      )}
                    >
                      {"Contact"}
                    </a>

                    <a
                      className={classNames(
                        projectcss.all,
                        projectcss.a,
                        projectcss.__wab_text,
                        sty.link__hJd0X
                      )}
                    >
                      {"Blog"}
                    </a>
                  </div>

                  <div
                    className={classNames(projectcss.all, sty.column__ukiLi)}
                  >
                    <h5
                      className={classNames(
                        projectcss.all,
                        projectcss.h5,
                        projectcss.__wab_text,
                        sty.h5___7EC6W
                      )}
                    >
                      {"Gallery"}
                    </h5>

                    <div
                      className={classNames(projectcss.all, sty.columns__mcbJa)}
                    >
                      <div
                        className={classNames(
                          projectcss.all,
                          sty.column__fPxwD
                        )}
                      >
                        <p.PlasmicImg
                          alt={""}
                          className={classNames(sty.img__mJgVd)}
                          displayHeight={"auto"}
                          displayMaxHeight={"none"}
                          displayMaxWidth={"100%"}
                          displayMinHeight={"0"}
                          displayMinWidth={"0"}
                          displayWidth={"auto"}
                          loading={"lazy"}
                          src={{
                            src: image41V5ADj4V6Z9I,
                            fullWidth: 390,
                            fullHeight: 290,
                            aspectRatio: undefined
                          }}
                        />
                      </div>

                      <div
                        className={classNames(
                          projectcss.all,
                          sty.column__q2XGw
                        )}
                      >
                        <p.PlasmicImg
                          alt={""}
                          className={classNames(sty.img___9NnR2)}
                          displayHeight={"auto"}
                          displayMaxHeight={"none"}
                          displayMaxWidth={"100%"}
                          displayMinHeight={"0"}
                          displayMinWidth={"0"}
                          displayWidth={"auto"}
                          loading={"lazy"}
                          src={{
                            src: image42CDeLRjSyJqx,
                            fullWidth: 390,
                            fullHeight: 290,
                            aspectRatio: undefined
                          }}
                        />
                      </div>

                      <div
                        className={classNames(
                          projectcss.all,
                          sty.column__tDFyF
                        )}
                      >
                        <p.PlasmicImg
                          alt={""}
                          className={classNames(sty.img__xWlKj)}
                          displayHeight={"auto"}
                          displayMaxHeight={"none"}
                          displayMaxWidth={"100%"}
                          displayMinHeight={"0"}
                          displayMinWidth={"0"}
                          displayWidth={"auto"}
                          loading={"lazy"}
                          src={{
                            src: image431JzadiWRtpu,
                            fullWidth: 390,
                            fullHeight: 290,
                            aspectRatio: undefined
                          }}
                        />
                      </div>
                    </div>

                    <div
                      className={classNames(projectcss.all, sty.columns__f8AZ)}
                    >
                      <div
                        className={classNames(
                          projectcss.all,
                          sty.column__cC5XU
                        )}
                      >
                        <p.PlasmicImg
                          alt={""}
                          className={classNames(sty.img__a4CRj)}
                          displayHeight={"auto"}
                          displayMaxHeight={"none"}
                          displayMaxWidth={"100%"}
                          displayMinHeight={"0"}
                          displayMinWidth={"0"}
                          displayWidth={"auto"}
                          loading={"lazy"}
                          src={{
                            src: image41V5ADj4V6Z9I,
                            fullWidth: 390,
                            fullHeight: 290,
                            aspectRatio: undefined
                          }}
                        />
                      </div>

                      <div
                        className={classNames(
                          projectcss.all,
                          sty.column__c0HJs
                        )}
                      >
                        <p.PlasmicImg
                          alt={""}
                          className={classNames(sty.img__hcJFf)}
                          displayHeight={"auto"}
                          displayMaxHeight={"none"}
                          displayMaxWidth={"100%"}
                          displayMinHeight={"0"}
                          displayMinWidth={"0"}
                          displayWidth={"auto"}
                          loading={"lazy"}
                          src={{
                            src: image42CDeLRjSyJqx,
                            fullWidth: 390,
                            fullHeight: 290,
                            aspectRatio: undefined
                          }}
                        />
                      </div>

                      <div
                        className={classNames(
                          projectcss.all,
                          sty.column__sSben
                        )}
                      >
                        <p.PlasmicImg
                          alt={""}
                          className={classNames(sty.img__tmIk9)}
                          displayHeight={"auto"}
                          displayMaxHeight={"none"}
                          displayMaxWidth={"100%"}
                          displayMinHeight={"0"}
                          displayMinWidth={"0"}
                          displayWidth={"auto"}
                          loading={"lazy"}
                          src={{
                            src: image431JzadiWRtpu,
                            fullWidth: 390,
                            fullHeight: 290,
                            aspectRatio: undefined
                          }}
                        />
                      </div>
                    </div>
                  </div>
                </div>
              </div>
            </div>

            <div
              data-plasmic-name={"footerBottom"}
              data-plasmic-override={overrides.footerBottom}
              className={classNames(projectcss.all, sty.footerBottom)}
            >
              <div
                data-plasmic-name={"container2"}
                data-plasmic-override={overrides.container2}
                className={classNames(projectcss.all, sty.container2)}
              >
                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__mwNk
                  )}
                >
                  <React.Fragment>
                    <React.Fragment>
                      {
                        "© Company Name. All rights reserved. This site proudly built with "
                      }
                    </React.Fragment>
                    {
                      <a
                        className={classNames(
                          projectcss.all,
                          projectcss.a,
                          projectcss.__wab_text,
                          projectcss.plasmic_default__inline,
                          sty.link__zewBf
                        )}
                        href={"https://www.plasmic.app/"}
                      >
                        {"Plasmic"}
                      </a>
                    }

                    <React.Fragment>{"."}</React.Fragment>
                  </React.Fragment>
                </div>
              </div>
            </div>
          </div>
        </p.Stack>
      </div>
    </React.Fragment>
  );
}

const PlasmicDescendants = {
  root: [
    "root",
    "pageBanner",
    "h1",
    "section",
    "foreground",
    "copy",
    "art",
    "h2",
    "footerTop",
    "container",
    "footerBottom",
    "container2"
  ],

  pageBanner: ["pageBanner", "h1"],
  h1: ["h1"],
  section: ["section", "foreground"],
  foreground: ["foreground"],
  copy: ["copy"],
  art: ["art"],
  h2: ["h2"],
  footerTop: ["footerTop", "container"],
  container: ["container"],
  footerBottom: ["footerBottom", "container2"],
  container2: ["container2"]
};

function makeNodeComponent(nodeName) {
  const func = function (props) {
    const { variants, args, overrides } = React.useMemo(
      () =>
        deriveRenderOpts(props, {
          name: nodeName,
          descendantNames: [...PlasmicDescendants[nodeName]],
          internalArgPropNames: PlasmicFeaturesPage__ArgProps,
          internalVariantPropNames: PlasmicFeaturesPage__VariantProps
        }),
      [props, nodeName]
    );

    return PlasmicFeaturesPage__RenderFunc({
      variants,
      args,
      overrides,
      forNode: nodeName
    });
  };
  if (nodeName === "root") {
    func.displayName = "PlasmicFeaturesPage";
  } else {
    func.displayName = `PlasmicFeaturesPage.${nodeName}`;
  }
  return func;
}

export const PlasmicFeaturesPage = Object.assign(
  // Top-level PlasmicFeaturesPage renders the root element
  makeNodeComponent("root"),
  {
    // Helper components rendering sub-elements
    pageBanner: makeNodeComponent("pageBanner"),
    h1: makeNodeComponent("h1"),
    section: makeNodeComponent("section"),
    foreground: makeNodeComponent("foreground"),
    copy: makeNodeComponent("copy"),
    art: makeNodeComponent("art"),
    h2: makeNodeComponent("h2"),
    footerTop: makeNodeComponent("footerTop"),
    container: makeNodeComponent("container"),
    footerBottom: makeNodeComponent("footerBottom"),
    container2: makeNodeComponent("container2"),
    // Metadata about props expected for PlasmicFeaturesPage
    internalVariantProps: PlasmicFeaturesPage__VariantProps,
    internalArgProps: PlasmicFeaturesPage__ArgProps,
    // Page metadata
    pageMetadata: {
      title: "",
      description: "",
      ogImageSrc: "",
      canonical: ""
    }
  }
);

export default PlasmicFeaturesPage;
/* prettier-ignore-end */
